# Enable tab completion
source ~/.dotfiles/profile/git-completion.bash

# colors!
green="\[\033[0;32m\]"
blue="\[\033[0;34m\]"
purple="\[\033[0;35m\]"
reset="\[\033[0m\]"

#export PATH = "/bin:$PATH"
#export PATH = "/usr/bin:$PATH"
#export PATH = "/usr/local/bin:$PATH"
#export PATH = "/sbin:$PATH"
#export PATH = "/usr/sbin:$PATH"
#export PATH = "/usr/local/sbin:$PATH"

manpdf() {
  man -t "$1" | open -f -a /Applications/Preview.app/
}

alias flushdns="dscacheutil -flushcache && killall -HUP mDNSResponder"

alias cleanupds="find . -type f -name '*.DS_Store' -ls -exec /bin/rm {} \;"
alias cleanupad="find . -type d -name '.AppleD*' -ls -exec /bin/rm -r {} \;"
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'


# Create a new directory and enter it

mk() {
  mkdir -p "$@" && cd "$@"
}

# Fuzzy find file/dir

ff() {  find . -type f -iname "$1";}
fff() { find . -type f -iname "*$1*";}
fd() {  find . -type d -iname "$1";}
fdf() { find . -type d -iname "*$1*";}

# Because SourceTree's $PATH gets screwed up starting it normally...
alias st="open /Applications/SourceTree.app/Contents/MacOS/SourceTree";
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl";
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code";

# Remove duplicates (preserving prepended items)
# Source: http://unix.stackexchange.com/a/40755
PATH=$(echo -n $PATH | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}')

# Change command prompt
source ~/.dotfiles/profile/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
export PS1="$purple\u$green\$(__git_ps1)$blue \W $ $reset"

